### ISSUE TITLE
[Sad😞]my freexe.py build command not works

### ISSUE THREAD

**Issue by chimoveon** [dmnfarrell/pandastable#127]
Very interested in pandastable, a great project, but a little problem in freeze.py 
Running freeze.py not works. My command in cmd is:  **python freeze.py build**

Everything looks all right in building process.
But after building, click the DataExplore.exe in my build folder, GUI not showing, doesn't work anyway.
By the way, my build folder is 845MB BIG!!!

↓↓↓building: no bugs and warning↓↓↓
![image](https://user-images.githubusercontent.com/26806915/54864283-2ac9ac00-4d90-11e9-8677-001d4adc953b.png)

↓↓↓My build folder↓↓↓
![image](https://user-images.githubusercontent.com/26806915/54864304-68c6d000-4d90-11e9-944f-43306a95eadd.png)

Env: python3.7, win10, nothing changed in source code. Running ok in pycharm.
So, may I ask what can I do to solve the issue ? Thank u so much  @dmnfarrell 
And the official pandastable msi file only 50MB，what you guys doing to make the dependency so small?

Also, hooks.py in cx_freeze below:
![image](https://user-images.githubusercontent.com/26806915/54864639-ee4c7f00-4d94-11e9-8175-da095b35eb3a.png)

**Comment by dmnfarrell** [comment]
I do not include scipy in the freeze so those hooks are not relevant. I am not sure why your build folder is so big. You appear to have a lot of dll files that I don't recognise. Perhaps because you use anaconda. The msi is compressed but the build folder should not take up more than 150MB or so. You can run the exe in a console and it may show the error.
Freezing is a bit hit and miss depending on your system. I did not use anaconda and built on windows 7. I need to test it on windows 10.

**Comment by chimoveon** [comment]
> I do not include scipy in the freeze so those hooks are not relevant. I am not sure why your build folder is so big. You appear to have a lot of dll files that I don't recognise. Perhaps because you use anaconda. The msi is compressed but the build folder should not take up more than 150MB or so. You can run the exe in a console and it may show the error.
> Freezing is a bit hit and miss depending on your system. I did not use anaconda and built on windows 7. I need to test it on windows 10.

**Comment by chimoveon** [comment]
Sorry, mistake close the issue.
Thank u so much for quick response.
I will try to figure out why things goes wrong in anaconda.
