### ISSUE TITLE
Keeping trailing zeroes that meet floatprecision value.

### ISSUE THREAD

**Issue by dbellistri** [dmnfarrell/pandastable#189]
Hi Damien,

Is there any way to show the trailing zeroes on the table?
Currently, if I use **"floatprecision":3** in  **config.apply_options()** the trailing zeroes will be removed.
E.g. show **0.500** even when the value is **0.5**?
Thanks.

Domenico

**Comment by dmnfarrell** [comment]
No there isn't an option to have trailing zeroes. I usually advise people to subclass the table to change these things.
In this case you can override the `table.setPrecision` method that is used in `redraw` to set the float precision. Just replace it to use your own format. You will need to update as I have moved this method out of the redraw function so that it can be conveniently re-used.

**Comment by dbellistri** [comment]
Thank you Damien!
