### ISSUE TITLE
date time index does not plot well and treated as string

### ISSUE THREAD

**Issue by chanansh** [dmnfarrell/pandastable#32]
when I try to plot a value vs. time it seems like the x-ticks treat the index date time as string rather than a datetime64. I used the internal conversion to datetime64 before plotting.
Moreover, I cannot seem to put plots grouped by in one plot with different colors rather than multiple plots.

**Comment by dmnfarrell** [comment]
Yes datetime support still needs some work. For example date parsers for importing. This is presumably due to your date format being recognised correctly. You would have to give me a sample of the data you imported so I can replicate the problem.
The grouped plots is separate but I know what you mean. However how do you see this working when plotting multiple columns and grouped in a single plot? I will make a new issue for that.

**Comment by dmnfarrell** [comment]
Old issue but the datetime problem is partly fixed with a new dialog for converting time data in the column header context menu.
