### ISSUE TITLE
SubTables/Two tables with same data frame

### ISSUE THREAD

**Issue by ljstrnadiii** [dmnfarrell/pandastable#44]
Hi dmnfarrell,

I have been working on trying to make a subtable that is editable so that it is actually editing the main table. The idea is to jump the user right to the error that need to be corrected so that he can double click edit and press enter. My problem is that when I make two Tables: one with a df and the other with df.loc[1,1], for example, editing and updating the second table does not change the df of the original table. Does Table copy the df? Any suggestions of how to make an editable subtable that effects the original table? I am aware this is not an issue, i do not think, but I could really use some help and do not mind deleting if we delete this...

**Comment by dmnfarrell** [comment]
Hi, The sub-table is editable but it is a copy and not linked to the main one. You could implement what you're trying to do as a plugin or are you trying to embed this functionality in your own application? It sounds like it wouldn't be too hard. If you look at the code for createChildTable it takes whatever df is passed to it, so you could pass the current dataframe to it rather than a copy. You would have to make sure you redraw both tables when you do an edit on the second one if I understand what you want correctly.

**Comment by ljstrnadiii** [comment]
I would like to embed the functionality in my own application. So far it has been great and I appreciate all your work! Ideally, I want the program to loop over some slices of a df and make a new table for each of these slices so that it can be edited and saved, editing and saving the main df. Instead of making a totally new Table passing the sliced df you think I should make a childTable? What object loaded with df.loc[1:3,:] (for example) will edit and update the main df from the main Table?

**Comment by ljstrnadiii** [comment]
I fixed the problem by making two separate table objects and added the changes from the second table that was a subset by calling on the table objects df attribute and using df1.update(df2). I am sorry for congesting the issues section without there being a real issue.

**Comment by dmnfarrell** [comment]
No problem. It qualifies as an issue I think! Glad you got a solution.
