### ISSUE TITLE
DataExplore crashes when called from python

### ISSUE THREAD

**Issue by MikeKilo** [dmnfarrell/pandastable#54]
Using python 3.6 and trying to create an instance of DataExplore, the application opens and a sheet with the dataframe appears, however the application does not respond and has to be killed.

**Comment by dmnfarrell** [comment]
Is there any error message? Are you calling this from a script or the python interpreter? You would have to show the specific code used.

**Comment by MikeKilo** [comment]
No error messages - I run this code:
`from pandastable.app import DataExplore
app = DataExplore()
app.load_dataframe(mhdf,'new')`
The application starts and a tabe named "new" is created, but the application stops responding, and when closing it, the python kernel dies with it.
the dataframe size does not matter as well - the current one was 500x6.

running python 3.6 over spyder 3.1.2.

**Comment by dmnfarrell** [comment]
I think this is simply because I didn't document how to do it properly. If you used the normal python interpreter it will not let you interact with the app until you call app.mainloop(). However this blocks further commands in the terminal. You can only get this to work without it blocking using ipython. You launch ipython and then type %gui tk. Then run app = DataExplore() and you should still be able to access the interpreter and interact with the app. I tried this in spyder ipython console too and it appears to work except the app is not visible! Maybe you can try it.

**Comment by badiay** [comment]
Trying to just load the main frame (on Spyder too). 
When I don't do the "%gui tk" it loads but crash but when I do it, it doesn't crash but doesn't show neither. How could you show it with the "%gui tk" ? 

("(Ne répond pas)" means doesn't respond (French Windows here) )
![capture](https://cloud.githubusercontent.com/assets/21133883/23508718/514fb6ea-ff53-11e6-88da-24697a06f40e.PNG)

**Comment by dmnfarrell** [comment]
@badiay This doesn't seem to work on windows using conda. It works on linux.

**Comment by xnmp** [comment]
I'm doing this from IPython console and it results in the same thing. I can't even kill it, but when I kill the kernel it dies as well.

**Comment by dmnfarrell** [comment]
What OS and are you using conda?

**Comment by Robuko** [comment]
running python 2.7.14 on spyder 3.2.4 on windows with tk backend for IPython, the app is not visible
