### ISSUE TITLE
Misleading scales in shared-y histogram

### ISSUE THREAD

**Issue by aivarannamaa** [dmnfarrell/pandastable#65]
I was experimenting with dataexplore (0.7.2, standalone app) using Titanic dataset. When I plotted ages by sex, I got following:

![pilt](https://user-images.githubusercontent.com/1802/27764852-80c4f7f6-5eac-11e7-8879-7e5404fe5b29.png)

I wanted to see the heights of the bars on the same scale so I clicked "share y" checbox and refreshed the plot. Unfortunately this simply removed the y-labels from the second histogram, without rescaling the bars:

![pilt](https://user-images.githubusercontent.com/1802/27764871-c242fdd6-5eac-11e7-8af5-a45c61a7294c.png)

**Comment by dmnfarrell** [comment]
Yes this is a result of the way the grouped plots are done. It might be fixable. I'll have a look.

**Comment by dmnfarrell** [comment]
This should be fixed now for both x and y axes in most plot types. If you're using the windows installed app you won't be able to check until I've made a new release though. I'll do that soon. Otherwise you could test the current git version.

![image](https://user-images.githubusercontent.com/7859189/27909219-94bbd7e0-6247-11e7-9664-2c9362c7b6d6.png)
